/**
 * NSE sector mapping — authoritative from NSE sector indices.
 *
 * Data source: NSE's public equity-stockIndices API, fetched via
 * scripts/lib/nse-http.mjs, covering NIFTY BANK, NIFTY FIN SERVICES,
 * NIFTY IT, NIFTY AUTO, NIFTY FMCG, NIFTY PHARMA, NIFTY METAL,
 * NIFTY REALTY, NIFTY ENERGY, NIFTY OIL & GAS, NIFTY MEDIA,
 * NIFTY INFRASTRUCTURE, NIFTY PSE, NIFTY CONSUMER DURABLES,
 * NIFTY PRIVATE BANK, NIFTY PSU BANK, NIFTY HEALTHCARE INDEX.
 *
 * This covers all major large-cap and mid-cap stocks across the
 * NSE universe (not just NIFTY SMALLCAP 100). NIFTY TOTAL MARKET
 * small caps that aren't in any sector index fall through to
 * sector=null, which the pipeline treats as "neutral sector info"
 * (doesn't block the trade, just doesn't contribute sector strength).
 *
 * Used by:
 *   - pattern/risk engines: read sector intraday strength alongside
 *     stock and NIFTY direction
 *   - CLI / browser sims: load the matching sector index candles
 *     so per-bar lookups are available without lookahead
 *
 * To refresh: re-run the NSE sector fetch script (which writes to
 * /tmp/sector_map.json) and regenerate this file.
 */

/** Yahoo symbols for NIFTY sector indices that have reliable 1m data. */
export const SECTOR_INDEX_SYMBOLS = {
  BANK: '^NSEBANK',
  FIN: 'NIFTY_FIN_SERVICE.NS',
  IT: '^CNXIT',
  AUTO: '^CNXAUTO',
  FMCG: '^CNXFMCG',
  PHARMA: '^CNXPHARMA',
  METAL: '^CNXMETAL',
  REALTY: '^CNXREALTY',
  ENERGY: '^CNXENERGY',
  MEDIA: '^CNXMEDIA',
  INFRA: '^CNXINFRA',
  PSE: '^CNXPSE',
  // CONSUMER has no Yahoo 1m data — included in the mapping for tagging
  // but no sector index candles available. Falls through gracefully.
};

/**
 * Stock → sector mapping, generated from NSE sector indices.
 * 208 stocks classified. Stocks not in this map return
 * null (unmapped) and the pipeline treats them as sector-neutral.
 */
export const STOCK_SECTOR = {
  "ABB": "ENERGY",
  "ABBOTINDIA": "PHARMA",
  "ABREL": "REALTY",
  "ADANIENSOL": "ENERGY",
  "ADANIENT": "METAL",
  "ADANIGREEN": "ENERGY",
  "ADANIPORTS": "INFRA",
  "ADANIPOWER": "ENERGY",
  "AEGISLOG": "ENERGY",
  "AJANTPHARM": "PHARMA",
  "ALKEM": "PHARMA",
  "AMBER": "CONSUMER",
  "AMBUJACEM": "INFRA",
  "ANANTRAJ": "REALTY",
  "APLAPOLLO": "METAL",
  "APOLLOHOSP": "PHARMA",
  "ASHOKLEY": "AUTO",
  "ATGL": "ENERGY",
  "AUBANK": "BANK",
  "AUROPHARMA": "PHARMA",
  "AXISBANK": "BANK",
  "BAJAJ-AUTO": "AUTO",
  "BAJAJFINSV": "FIN",
  "BAJFINANCE": "FIN",
  "BANDHANBNK": "BANK",
  "BANKBARODA": "BANK",
  "BANKINDIA": "BANK",
  "BATAINDIA": "CONSUMER",
  "BEL": "PSE",
  "BHARATFORG": "AUTO",
  "BHARTIARTL": "INFRA",
  "BHEL": "ENERGY",
  "BIOCON": "PHARMA",
  "BLUESTARCO": "CONSUMER",
  "BOSCHLTD": "AUTO",
  "BPCL": "ENERGY",
  "BRIGADE": "REALTY",
  "BRITANNIA": "FMCG",
  "BSE": "FIN",
  "CANBK": "BANK",
  "CASTROLIND": "ENERGY",
  "CENTRALBK": "BANK",
  "CESC": "ENERGY",
  "CGPOWER": "ENERGY",
  "CHENNPETRO": "ENERGY",
  "CHOLAFIN": "FIN",
  "CIPLA": "PHARMA",
  "COALINDIA": "ENERGY",
  "COFORGE": "IT",
  "COLPAL": "FMCG",
  "CONCOR": "PSE",
  "CROMPTON": "CONSUMER",
  "CUMMINSIND": "INFRA",
  "DABUR": "FMCG",
  "DBCORP": "MEDIA",
  "DIVISLAB": "PHARMA",
  "DIXON": "CONSUMER",
  "DLF": "REALTY",
  "DRREDDY": "PHARMA",
  "EICHERMOT": "AUTO",
  "EMAMILTD": "FMCG",
  "ENRIN": "ENERGY",
  "EXIDEIND": "AUTO",
  "FEDERALBNK": "BANK",
  "FORTIS": "PHARMA",
  "GAIL": "ENERGY",
  "GLAND": "PHARMA",
  "GLENMARK": "PHARMA",
  "GODREJCP": "FMCG",
  "GODREJPROP": "REALTY",
  "GRASIM": "INFRA",
  "GSPL": "ENERGY",
  "GVT&D": "ENERGY",
  "HAL": "PSE",
  "HATHWAY": "MEDIA",
  "HAVELLS": "CONSUMER",
  "HCLTECH": "IT",
  "HDFCBANK": "BANK",
  "HDFCLIFE": "FIN",
  "HEROMOTOCO": "AUTO",
  "HINDALCO": "METAL",
  "HINDCOPPER": "METAL",
  "HINDPETRO": "ENERGY",
  "HINDUNILVR": "FMCG",
  "HINDZINC": "METAL",
  "ICICIBANK": "BANK",
  "ICICIGI": "FIN",
  "IDFCFIRSTB": "BANK",
  "IGL": "ENERGY",
  "INDHOTEL": "INFRA",
  "INDIANB": "BANK",
  "INDIGO": "INFRA",
  "INDUSINDBK": "BANK",
  "INDUSTOWER": "INFRA",
  "INFY": "IT",
  "INOXWIND": "ENERGY",
  "IOB": "BANK",
  "IOC": "ENERGY",
  "IPCALAB": "PHARMA",
  "IRCTC": "PSE",
  "IRFC": "PSE",
  "ITC": "FMCG",
  "JBCHEPHARM": "PHARMA",
  "JINDALSTEL": "METAL",
  "JIOFIN": "FIN",
  "JPPOWER": "ENERGY",
  "JSL": "METAL",
  "JSWENERGY": "ENERGY",
  "JSWSTEEL": "METAL",
  "KAJARIACER": "CONSUMER",
  "KALYANKJIL": "CONSUMER",
  "KOTAKBANK": "BANK",
  "LAURUSLABS": "PHARMA",
  "LGEINDIA": "CONSUMER",
  "LICHSGFIN": "FIN",
  "LLOYDSME": "METAL",
  "LODHA": "REALTY",
  "LT": "INFRA",
  "LTM": "IT",
  "LUPIN": "PHARMA",
  "M&M": "AUTO",
  "MAHABANK": "BANK",
  "MANKIND": "PHARMA",
  "MARICO": "FMCG",
  "MARUTI": "AUTO",
  "MAXHEALTH": "PHARMA",
  "MFSL": "FIN",
  "MGL": "ENERGY",
  "MOTHERSON": "AUTO",
  "MPHASIS": "IT",
  "MUTHOOTFIN": "FIN",
  "NATIONALUM": "METAL",
  "NAZARA": "MEDIA",
  "NESTLEIND": "FMCG",
  "NETWORK18": "MEDIA",
  "NHPC": "ENERGY",
  "NLCINDIA": "ENERGY",
  "NMDC": "METAL",
  "NTPC": "ENERGY",
  "NTPCGREEN": "ENERGY",
  "OBEROIRLTY": "REALTY",
  "OFSS": "IT",
  "OIL": "ENERGY",
  "ONGC": "ENERGY",
  "PATANJALI": "FMCG",
  "PERSISTENT": "IT",
  "PETRONET": "ENERGY",
  "PFC": "FIN",
  "PFOCUS": "MEDIA",
  "PGEL": "CONSUMER",
  "PHOENIXLTD": "REALTY",
  "PNB": "BANK",
  "POWERGRID": "ENERGY",
  "POWERINDIA": "ENERGY",
  "PPLPHARMA": "PHARMA",
  "PRESTIGE": "REALTY",
  "PSB": "BANK",
  "PVRINOX": "MEDIA",
  "RADICO": "FMCG",
  "RBLBANK": "BANK",
  "RECLTD": "FIN",
  "RELIANCE": "ENERGY",
  "RPOWER": "ENERGY",
  "RVNL": "PSE",
  "SAIL": "METAL",
  "SAREGAMA": "MEDIA",
  "SBICARD": "FIN",
  "SBILIFE": "FIN",
  "SBIN": "BANK",
  "SHREECEM": "INFRA",
  "SHRIRAMFIN": "FIN",
  "SIEMENS": "ENERGY",
  "SJVN": "ENERGY",
  "SOBHA": "REALTY",
  "SONACOMS": "AUTO",
  "SUNPHARMA": "PHARMA",
  "SUNTV": "MEDIA",
  "SUZLON": "ENERGY",
  "SYNGENE": "PHARMA",
  "TATACONSUM": "FMCG",
  "TATAPOWER": "ENERGY",
  "TATASTEEL": "METAL",
  "TCS": "IT",
  "TECHM": "IT",
  "THERMAX": "ENERGY",
  "TIINDIA": "AUTO",
  "TIPSMUSIC": "MEDIA",
  "TITAN": "CONSUMER",
  "TMPV": "AUTO",
  "TORNTPHARM": "PHARMA",
  "TORNTPOWER": "ENERGY",
  "TVSMOTOR": "AUTO",
  "UBL": "FMCG",
  "UCOBANK": "BANK",
  "ULTRACEMCO": "INFRA",
  "UNIONBANK": "BANK",
  "UNITDSPR": "FMCG",
  "UNOMINDA": "AUTO",
  "VBL": "FMCG",
  "VEDL": "METAL",
  "VOLTAS": "CONSUMER",
  "WELCORP": "METAL",
  "WHIRLPOOL": "CONSUMER",
  "WIPRO": "IT",
  "WOCKPHARMA": "PHARMA",
  "YESBANK": "BANK",
  "ZEEL": "MEDIA",
  "ZYDUSLIFE": "PHARMA",
};

/** @returns {string | null} sector key for a given symbol, or null. */
export function getSector(symbol) {
  if (!symbol) return null;
  const sym = String(symbol).toUpperCase().replace(/.NS$/, '');
  return STOCK_SECTOR[sym] || null;
}

/** @returns {string | null} Yahoo sector index symbol for a sector key. */
export function getSectorIndexSymbol(sectorKey) {
  if (!sectorKey) return null;
  return SECTOR_INDEX_SYMBOLS[sectorKey] || null;
}
